version: '3.7'

services:
  etcd:
    image: bitnami/etcd:3.5.4
    container_name: etcd
    environment:
      - ETCD_ENABLE_V2=true
      - ETCD_ROOT_PASSWORD=Ai*()890
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    volumes:
      - ./data/etcd:/bitnami/etcd
    ports:
      - "2379:2379"
    restart: always
#    networks:
#      - apisix-network

  # APISIX 是核心 API 网关服务
  apisix:
    image: tyronextian/apisix:3.10.0-debian
    container_name: apisix
    ports:
      - "8000:9080"  # 外部请求访问 API 网关
#      - "9443:9443"  # 外部请求访问 API 网关（HTTPS）
    volumes:
      - ./data/log/apisix:/usr/local/apisix/logs
      - ./conf/apisix/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    restart: always
#    networks:
#      - apisix-network

  apisix-dashboard:
    image: apache/apisix-dashboard:latest
    container_name: apisix-dashboard
    environment:
      - APISIX_BASE_URL=http://apisix:8080  # 配置 APISIX 网关地址
      - ETCD_HOST=etcd:2379  # 配置 ETCD 地址
    ports:
      - "9000:9000"  # 访问 Dashboard 管理界面的端口
    volumes:
      - ./conf/dashboard/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    depends_on:
      - apisix
      - etcd
    restart: always
#    networks:
#      - apisix-network


#networks:
#  apisix-network:
#    external: true


