version: '3.7'

services:
  # ETCD 是 APISIX 的配置存储
  etcd:
    image: bitnami/etcd:3.5.4
    container_name: etcd
    hostname: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
#      - ETCD_ADVERTISE_CLIENT_URLS="http://0.0.0.0:2379"
#      - ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379"
    ports:
      - "2379:2379"
    volumes:
      - etcd-data:/etcd-data
    restart: always
    networks:
      - apisix-network

  # APISIX 是核心 API 网关服务
  apisix:
    image: apache/apisix:3.11.0-debian
    container_name: apisix
    ports:
      - "9080:9080"  # 外部请求访问 API 网关
#      - "9443:9443"  # 外部请求访问 API 网关（HTTPS）
    volumes:
      - ./data/log:/usr/local/apisix/logs
      - ./conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    restart: always
    networks:
      - apisix-network

  apisix-dashboard:
    image: apache/apisix-dashboard:latest
    container_name: apisix-dashboard
    environment:
      - APISIX_BASE_URL=http://apisix:9080  # 配置 APISIX 网关地址
      - ETCD_HOST=etcd:2379  # 配置 ETCD 地址
    ports:
      - "9000:9000"  # 访问 Dashboard 管理界面的端口
    volumes:
      - ./conf/dashboard/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    depends_on:
      - apisix
      - etcd
    restart: always
    networks:
      - apisix-network


volumes:
  etcd-data:
    driver: local

networks:
  apisix-network:
    driver: bridge